{% set name = "ecco_access" %}
{% set version = "0.2.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecco_access-{{ version }}.tar.gz
  sha256: 478dc88bf46ec59eb70d72c6abf4aee20818085a53afcc48c897c30dbd75ccd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80
    - wheel
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - future
    - dask-core
    - fsspec >=2024.12.0
    - netcdf4
    - pandas
    - python-dateutil
    - requests
    - s3fs >=2024.12.0
    - tqdm
    - xarray
    - zarr >=3.0.7
    - pyresample

test:
  imports:
    - ecco_access
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ECCO-GROUP/ECCO-ACCESS
  summary: Access utilities for ECCO state estimate output hosted on PO.DAAC and in the AWS cloud
  license: MIT
  license_file: LICENSE
  doc_url: https://ecco-access.readthedocs.io/
  dev_url: https://github.com/ECCO-GROUP/ECCO-ACCESS

extra:
  recipe-maintainers:
    - andrewdelman
